# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='blue',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='colors',
            name='green',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='colors',
            name='red',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='colors',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
